### ISSUE TITLE
[Bug] Issues with same global vars.

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeXPluginExample#1]
When PKHeX is loaded, and assuming there are 2 plugins following the same example plugin format, one of them will override the global variables such as Name, SaveFileEditor, PKMEditor etc.

The fix should be pretty straightforward, however i'll continue exploring more issues before I make a PR

**Comment by architdate** [comment]
![image](https://user-images.githubusercontent.com/17220860/40031460-63d17d84-5822-11e8-97b3-0f565ad337ff.png)
here is an example of what I am talking about btw, one of those is supposed to be `ExamplePlugin` from this repository

**Comment by architdate** [comment]
![image](https://user-images.githubusercontent.com/17220860/40031582-ee530ab8-5822-11e8-90f4-8f812c05f431.png)
This is my directory structure

**Comment by kwsch** [comment]
All plugins receive the same parameters when initialzed; a reference to the SAVEditor (ISaveProvider), a reference to the PKMEditor (IPKMView) and the main menu's toolstrip ribbon. All are objects inside the Main window.

Do the two tested plugins have the same Class / Namespace / Assembly names? Probably is activating the same 'assembly' reference which is shared between the two dll's.

https://softwareengineering.stackexchange.com/a/112531

**Comment by architdate** [comment]
Ah yes it was the same assembly names since i ended up editing your example file itself.
After making a completely new plugin from scratch, I can see that the names are different
![image](https://user-images.githubusercontent.com/17220860/40033279-400ee62c-582a-11e8-8c0a-35adf0ce841a.png)
